[general]
import = ["~/font-size.toml", "~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "MononokiNerdFontMono"

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 12
y = 12
