import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 12
y = 12
