#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-0 --off
xrandr --output DP-0 --mode 3440x1440 --rate 144
xsetroot -cursor_name left_ptr
systemctl --user restart wireplumber pipewire pipewire-pulse

feh --bg-center ~/.config/assets/desktop.jpg

picom -b

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar main_bar --config=~/.config/polybar/config.ini &

bspc config border_width                0
bspc config window_gap                  16
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true

bspc monitor DP-0 -d 1 2 3 4 5

